### Crear Regla de Estado Necesario
# Para pasar al estado 3, primero debe haber pasado por el estado 1
POST http://localhost:3000/api/estados-necesarios
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "codEstado": 3,
  "codNecesario": 1
}

###

### Obtener todas las reglas
GET http://localhost:3000/api/estados-necesarios
//Authorization: Bearer {{accessToken}}

###

### Obtener reglas para un estado específico
GET http://localhost:3000/api/estados-necesarios/estado/3
//Authorization: Bearer {{accessToken}}

###

### Eliminar regla
DELETE http://localhost:3000/api/estados-necesarios/1
//Authorization: Bearer {{accessToken}}
