### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "goat",
  "password": "1234"
}

###

### Refresh Token
# POST http://localhost:3000/api/auth/refresh
# Content-Type: application/json

# {
#   "refreshToken": "{{refreshToken}}"
# }

###

### Get Current User (Me)
GET http://localhost:3000/api/auth/me
//Authorization: Bearer {{accessToken}}
