### Crear Tipo de Estado
POST http://localhost:3000/api/estados
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nombreEstado": "CHESS"
}

### Crear Tipo de Estado
POST http://localhost:3000/api/estados
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nombreEstado": "PENDIENTE"
}

### Crear Tipo de Estado
POST http://localhost:3000/api/estados
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nombreEstado": "EN PREPARACION"
}

### Crear Tipo de Estado
POST http://localhost:3000/api/estados
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nombreEstado": "PREPARADO"
}

### Crear Tipo de Estado
POST http://localhost:3000/api/estados
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nombreEstado": "PAGADO"
}

### Crear Tipo de Estado
POST http://localhost:3000/api/estados
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nombreEstado": "ENTREGADO"
}

###

### Obtener todos los tipos de estado
GET http://localhost:3000/api/estados
//Authorization: Bearer {{accessToken}}

###

### Obtener tipo de estado por código
GET http://localhost:3000/api/estados/4
//Authorization: Bearer {{accessToken}}

###

### Actualizar tipo de estado
PUT http://localhost:3000/api/estados/4
//Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "nombreEstado": "PAGADO"
}

###

### Eliminar tipo de estado
DELETE http://localhost:3000/api/estados/4
//Authorization: Bearer {{accessToken}}
