### Variables
@baseUrl = http://localhost:3000/api
@contentType = application/json

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "jarvis",
  "nombre": "Sistema",
  "apellido": "Automático",
  "sector": "CHESS",
  "password": "1234"
}

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "peter",
  "nombre": "Pedro",
  "apellido": "Gonzales",
  "sector": "Producción",
  "password": "1234"
}

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "goat",
  "nombre": "Lionel",
  "apellido": "Messi",
  "sector": "Producción",
  "password": "1234"
}

### Obtener todos los usuarios
GET {{baseUrl}}/usuarios
//Authorization: Bearer {{accessToken}}

###

### Obtener usuario por ID
GET {{baseUrl}}/usuarios/1
//Authorization: Bearer {{accessToken}}

###

### Actualizar usuario
PUT {{baseUrl}}/usuarios/1
//Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "username": "juanca",
  "nombre": "Juan Carlos",
  "sector": "Logística",
  "password": "abcd"
}

###

### Eliminar usuario
DELETE {{baseUrl}}/usuarios/2
//Authorization: Bearer {{accessToken}}
