### Variables
@baseUrl = http://localhost:3000/api
@contentType = application/json

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "jarvis",
  "nombre": "Sistema",
  "apellido": "Automático",
  "sector": "CHESS",
  "password": "1234"
}

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "peter",
  "nombre": "Pedro",
  "apellido": "Gonzales",
  "sector": "armado",
  "password": "1234"
}


### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "marce",
  "nombre": "Marcela",
  "apellido": "Macia",
  "sector": "facturacion",
  "password": "1234"
}
### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "goat",
  "nombre": "Lionel",
  "apellido": "Messi",
  "sector": "admin",
  "password": "1234"
}


### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "romi",
  "nombre": "Romina",
  "apellido": "Cosci",
  "sector": "admin",
  "password": "1234"
}


### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "username": "random",
  "nombre": "random",
  "apellido": "random",
  "sector": "facturacion",
  "password": "1234"
}


### Obtener todos los usuarios
GET {{baseUrl}}/usuarios
//Authorization: Bearer {{accessToken}}

###

### Obtener usuario por ID
GET {{baseUrl}}/usuarios/6
//Authorization: Bearer {{accessToken}}

###

### Actualizar usuario
PUT {{baseUrl}}/usuarios/6
//Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "username": "juanca",
  "nombre": "Juan Carlos",
  "sector": "facturacion",
  "password": "1224"
}

###

### Eliminar usuario
DELETE {{baseUrl}}/usuarios/2
//Authorization: Bearer {{accessToken}}
