### Variables
@baseUrl = http://localhost:3000/api
@contentType = application/json

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "sector": "Producción",
  "password": "1234"
}

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
  "nombre": "Pedro",
  "apellido": "Gonzales",
  "sector": "Producción",
  "password": "1234"
}

### Obtener todos los usuarios
GET {{baseUrl}}/usuarios
//Authorization: Bearer {{accessToken}}

###

### Obtener usuario por ID
GET {{baseUrl}}/usuarios/1
//Authorization: Bearer {{accessToken}}

###

### Actualizar usuario
PUT {{baseUrl}}/usuarios/1
//Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "nombre": "Juan Carlos",
  "sector": "Logística"
}

###

### Eliminar usuario
DELETE {{baseUrl}}/usuarios/1
//Authorization: Bearer {{accessToken}}
